batch_size: 100
consensus_threshold: 0.8
dataset_type: qa_pairs
deduplicate: true
description: High-quality science question-answer pairs for training
diversity_models:
- qwen2.5
generation_params:
  difficulty_levels:
  - beginner
  - intermediate
  - advanced
  max_tokens: 2048
  temperature: 0.7
  topics:
  - physics
  - chemistry
  - biology
  - earth_science
  - astronomy
max_retries: 3
models:
- llama3
- openchat
- deepseek-r1
name: Science QA Dataset
output_format: jsonl
quality_level: high
require_consensus: true
target_size: 10000
validation_model: deepseek-r1
